using Netus2_DatabaseConnection.dataObjects;
using Netus2_DatabaseConnection.dbAccess;
using System.Collections.Generic;

namespace Netus2_DatabaseConnection.daoInterfaces
{
    public interface IPhoneNumberDao
    {
        /// <summary>
        /// Sets the taskId value to be used in "write" and "update" statements, 
        /// to indicate which process made the modification to the database in the 
        /// "created_by" and "changed_by" fields, respectively.
        /// </summary>
        /// <param name="taskId"></param>
        void SetTaskId(int taskId);

        /// <summary>
        /// Returns the taskId value, used in "write" and "update" statements, 
        /// to indicate which process made the modification to the database in the 
        /// "created_by" and "changed_by" fields, respectively.
        /// </summary>
        /// <returns>Null, if no value has been set.</returns>
        int? GetTaskId();

        /// <summary>
        /// Deletes the provided record from the database.
        /// </summary>
        /// <param name="phoneNumber"></param>
        /// <param name="connection"></param>
        public void Delete(PhoneNumber phoneNumber, IConnectable connection);

        /// <summary>
        /// Queries the database for any records that match what is provided. Null datapoints are ignored.
        /// </summary>
        /// <param name="phoneNumber"></param>
        /// <param name="connection"></param>
        /// <returns></returns>
        public List<PhoneNumber> Read(PhoneNumber phoneNumber, IConnectable connection);

        /// <summary>
        /// Queries the database for the records associated with the passed-in data.
        /// </summary>
        /// <param name="personId"></param>
        /// <param name="connection"></param>
        /// <returns>Empty list, if no records are found.</returns>
        public List<PhoneNumber> Read_AllWithPersonId(int personId, IConnectable connection);

        /// <summary>
        /// <para>
        /// Queries the database for any records that match what is provided, and are linked 
        /// to the provided personId. Null datapoints are ignored.
        /// </summary>
        /// <param name="phoneNumber"></param>
        /// <param name="personId"></param>
        /// <param name="connection"></param>
        /// <returns>Empty list, if no records are found.</returns>
        public List<PhoneNumber> Read(PhoneNumber phoneNumber, int personId, IConnectable connection);

        /// <summary>
        /// <para>
        /// Checks to see if the provided data is associated to any record currently in the database.
        /// If not, then writes this record to the database, not linked to any Person record.
        /// If so, then updates the database record to match this object, setting any personId to null.
        /// </para>
        /// The personId is not used as part of the lookup phase.
        /// </summary>
        /// <param name="phoneNumber"></param>
        /// <param name="connection"></param>
        public void Update(PhoneNumber phoneNumber, IConnectable connection);

        /// <summary>
        /// <para>
        /// Checks to see if the provided data is associated to any record currently in the database.
        /// If not, then writes this record to the database, linked to the provided personId.
        /// If so, then updates the database record to match this object, including a link to the provided personId.
        /// </para>
        /// The personId is not used as part of the lookup phase.
        /// </summary>
        /// <param name="phoneNumber"></param>
        /// <param name="personId"></param>
        /// <param name="connection"></param>
        public void Update(PhoneNumber phoneNumber, int personId, IConnectable connection);

        /// <summary>
        /// Writes the provided record to the database.
        /// </summary>
        /// <param name="phoneNumber"></param>
        /// <param name="connection"></param>
        /// <returns>A copy of the record that was written, including the object Id, generated by the database.</returns>
        public PhoneNumber Write(PhoneNumber phoneNumber, IConnectable connection);

        /// <summary>
        /// Writes the provided record to the database, linked to the provided personId.
        /// </summary>
        /// <param name="phoneNumber"></param>
        /// <param name="personId"></param>
        /// <param name="connection"></param>
        /// <returns>A copy of the record that was written, including the object Id, generated by the database.</returns>
        public PhoneNumber Write(PhoneNumber phoneNumber, int personId, IConnectable connection);
    }
}