using Netus2_DatabaseConnection.dataObjects;
using Netus2_DatabaseConnection.dbAccess;
using System.Collections.Generic;

namespace Netus2_DatabaseConnection.daoInterfaces
{
    public interface IUniqueIdentifierDao
    {
        /// <summary>
        /// Sets the taskId value to be used in "write" and "update" statements, 
        /// to indicate which process made the modification to the database in the 
        /// "created_by" and "changed_by" fields, respectively.
        /// </summary>
        /// <param name="taskId"></param>
        void SetTaskId(int taskId);

        /// <summary>
        /// Returns the taskId value, used in "write" and "update" statements, 
        /// to indicate which process made the modification to the database in the 
        /// "created_by" and "changed_by" fields, respectively.
        /// </summary>
        /// <returns>Null, if no value has been set.</returns>
        int? GetTaskId();

        /// <summary>
        /// Deletes the provided record from the database.
        /// </summary>
        /// <param name="uniqueId"></param>
        /// <param name="connection"></param>
        public void Delete(UniqueIdentifier uniqueId, IConnectable connection);

        /// <summary>
        /// Queries the database for a specific record, using the primary key value.
        /// </summary>
        /// <param name="personId"></param>
        /// <param name="connection"></param>
        /// <returns>Null, if no record is found.</returns>
        public List<UniqueIdentifier> Read_AllWithPersonId(int personId, IConnectable connection);

        /// <summary>
        /// Queries the database for any records that match what is provided. Null datapoints are ignored.
        /// </summary>
        /// <param name="uniqueId"></param>
        /// <param name="personId"></param>
        /// <param name="connection"></param>
        /// <returns>Empty list, if no records are found.</returns>
        public List<UniqueIdentifier> Read(UniqueIdentifier uniqueId, int personId, IConnectable connection);

        /// <summary>
        /// Checks to see if the provided data is associated to any record currently in the database.
        /// If not, then writes this record to the database.
        /// If so, then updates the database record to match this object.
        /// </summary>
        /// <param name="uniqueIdentifier"></param>
        /// <param name="personId"></param>
        /// <param name="connection"></param>
        public void Update(UniqueIdentifier uniqueIdentifier, int personId, IConnectable connection);

        /// <summary>
        /// Writes the provided record to the database.
        /// </summary>
        /// <param name="uniqueId"></param>
        /// <param name="personId"></param>
        /// <param name="connection"></param>
        /// <returns>A copy of the record that was written, including the object Id, generated by the database.</returns>
        public UniqueIdentifier Write(UniqueIdentifier uniqueId, int personId, IConnectable connection);
    }
}